# Generated by Django 3.1.5 on 2021-05-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_comment', models.TextField(max_length=1000)),
                ('contact_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(default='', max_length=255)),
                ('Cost', models.FloatField(default=0.0)),
                ('Registration_start', models.DateField()),
                ('Registration_end', models.DateField()),
                ('Runner_quantity', models.IntegerField(default=0)),
                ('Event_logo', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='Eventlogo/')),
                ('Status', models.CharField(default='', max_length=50)),
                ('Description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_title', models.CharField(max_length=100)),
                ('website_description', models.CharField(max_length=256)),
                ('website_logo', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='Eventlogo/')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('button_name', models.CharField(max_length=256)),
                ('button_link', models.CharField(max_length=256)),
                ('background', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/')),
                ('front_img', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/')),
                ('front_img_two', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('SFname', models.CharField(default='First Name', max_length=100)),
                ('SLname', models.CharField(default='Last Name', max_length=100)),
                ('SEmail', models.CharField(default='Email Name', max_length=100)),
                ('SUsername', models.CharField(default='Username ', max_length=100)),
                ('SPassword', models.TextField(default='Password ', max_length=3000)),
                ('SContactNo', models.CharField(default='Contact no', max_length=100)),
                ('SProfile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Surname', models.CharField(default='', max_length=255)),
                ('Ci', models.CharField(default='', max_length=255)),
                ('Ruc', models.CharField(default='', max_length=255)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Phones', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Direction', models.CharField(default='', max_length=255)),
                ('City', models.CharField(default='', max_length=255)),
                ('Birth_date', models.DateField()),
                ('Creation', models.DateTimeField(auto_now_add=True)),
                ('Password', models.TextField(default='', max_length=500)),
                ('Token', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User_Event_Registration',
            fields=[
                ('Registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disable', 'Disable')], default='Disable', max_length=100)),
                ('EventId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Pending', max_length=100)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('EventTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('EventType', models.CharField(default='', max_length=255)),
                ('Super_AdminAccount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.super_adminaccount')),
            ],
        ),
        migrations.CreateModel(
            name='event_progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('meter', models.FloatField(default=0, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.FloatField(default=0.0)),
                ('running_point', models.IntegerField(default=0)),
                ('EventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='EventTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event_type'),
        ),
    ]
